/**
 * dummy-docs.js — 10種類以上のダミー業務文書＋業種別対応
 */
const dummyDocuments = [
  { title: '2026年度 第1四半期 事業計画書', industry: 'general', content: `<h1>2026年度 第1四半期 事業計画書</h1><p>本文書は、2026年度第1四半期における事業部門の主要施策および達成目標について取りまとめたものである。</p><h2>1. 経営環境の分析</h2><p>国内市場においては、DXの加速に伴いクラウドサービス需要が前年同期比で約23%増加している。人材確保の観点からは依然として厳しい状況が続いている。</p><h2>2. 重点施策</h2><h3>2.1 プロダクト開発の強化</h3><p>AI/ML機能を活用した新サービスの開発を推進する。</p><ul><li>新機能リリース: 3月末までに5件以上</li><li>ベータテスト参加企業: 20社以上</li><li>顧客満足度スコア: 4.2以上</li></ul><h2>3. 数値目標</h2><table><tr><th>指標</th><th>目標値</th><th>前年実績</th></tr><tr><td>売上高</td><td>15.2億円</td><td>12.8億円</td></tr><tr><td>営業利益率</td><td>18.5%</td><td>15.2%</td></tr><tr><td>新規顧客</td><td>45社</td><td>32社</td></tr></table><p>以上</p>` },
  { title: '第32回 定例ミーティング 議事録', industry: 'general', content: `<h1>第32回 定例ミーティング 議事録</h1><p><strong>日時:</strong> 2026年3月3日 10:00〜11:30</p><p><strong>場所:</strong> 本社 会議室A（Teams同時配信）</p><p><strong>出席者:</strong> 田中部長、佐藤課長、鈴木主任、高橋、山田</p><h2>1. 前回議事録の確認</h2><ul><li>【完了】API仕様書の改訂</li><li>【進行中】パフォーマンステスト環境の構築</li><li>【未着手】外部ベンダーとの契約更新</li></ul><h2>2. プロジェクト進捗</h2><p>マイクロサービス移行は全12サービスのうち8サービスが完了。レスポンスタイムが約40%改善。</p><h2>3. 次回アクションアイテム</h2><table><tr><th>No.</th><th>内容</th><th>担当</th><th>期限</th></tr><tr><td>1</td><td>移行スケジュール詳細化</td><td>鈴木</td><td>3/10</td></tr><tr><td>2</td><td>QAテスト計画書</td><td>山田</td><td>3/14</td></tr></table><p>以上</p>` },
  { title: '顧客対応マニュアル（改訂第3版）', industry: 'general', content: `<h1>顧客対応マニュアル（改訂第3版）</h1><p><strong>最終更新:</strong> 2026年2月28日</p><h2>1. 目的</h2><p>顧客からの問い合わせに対して一貫性のある高品質な対応を行うための手順を定める。</p><h2>2. 対応フロー</h2><ol><li>受領後30分以内に初回応答メールを送信</li><li>カテゴリ分類（技術/機能要望/契約/その他）</li><li>優先度判定（P1〜P4）</li></ol><h2>3. 対応時間</h2><table><tr><th>優先度</th><th>初回応答</th><th>解決目標</th></tr><tr><td>P1（緊急）</td><td>15分</td><td>4時間</td></tr><tr><td>P2（高）</td><td>30分</td><td>8時間</td></tr><tr><td>P3（通常）</td><td>2時間</td><td>24時間</td></tr></table><p>以上</p>` },
  { title: '2026年度 採用計画書', industry: 'general', content: `<h1>2026年度 採用計画書</h1><p><strong>策定日:</strong> 2026年1月15日</p><h2>1. 採用方針</h2><p>事業拡大に伴い、技術職を中心に年間30名の採用を目標とする。多様性の確保および即戦力人材の獲得を重点的に推進する。</p><h2>2. 職種別採用計画</h2><table><tr><th>職種</th><th>人数</th><th>時期</th></tr><tr><td>ソフトウェアエンジニア</td><td>15名</td><td>通年</td></tr><tr><td>プロダクトマネージャー</td><td>3名</td><td>Q1-Q2</td></tr><tr><td>データサイエンティスト</td><td>5名</td><td>Q1-Q3</td></tr><tr><td>カスタマーサクセス</td><td>4名</td><td>Q2-Q3</td></tr><tr><td>デザイナー</td><td>3名</td><td>Q1-Q2</td></tr></table><h2>3. 採用チャネル</h2><ul><li>リファラル採用制度の強化（紹介報酬の増額）</li><li>テックカンファレンスでのスポンサー出展</li><li>大学との産学連携プログラム</li></ul><p>以上</p>` },
  { title: 'セキュリティポリシー v2.1', industry: 'it', content: `<h1>情報セキュリティポリシー v2.1</h1><p><strong>施行日:</strong> 2026年4月1日</p><h2>1. 基本方針</h2><p>当社は情報セキュリティの確保を経営上の重要課題と位置付け、情報資産の機密性・完全性・可用性を維持する。</p><h2>2. アクセス管理</h2><ul><li>多要素認証(MFA)の全システムへの適用</li><li>最小権限の原則に基づくアクセス制御</li><li>90日ごとのアクセス権レビュー</li></ul><h2>3. インシデント対応</h2><p>セキュリティインシデント発生時は、情報セキュリティ委員会に30分以内に第一報を行うこと。</p><h2>4. 監査</h2><p>年次で外部監査法人による情報セキュリティ監査を実施し、SOC2 Type II認証を維持する。</p><p>以上</p>` },
  { title: '決算短信（2025年度第4四半期）', industry: 'finance', content: `<h1>2025年度 第4四半期 決算短信</h1><p><strong>発表日:</strong> 2026年2月14日</p><h2>1. 業績概要</h2><table><tr><th>項目</th><th>当期</th><th>前期</th><th>増減率</th></tr><tr><td>売上高</td><td>58.3億円</td><td>49.1億円</td><td>+18.7%</td></tr><tr><td>営業利益</td><td>10.5億円</td><td>7.8億円</td><td>+34.6%</td></tr><tr><td>経常利益</td><td>10.8億円</td><td>8.1億円</td><td>+33.3%</td></tr><tr><td>純利益</td><td>7.2億円</td><td>5.4億円</td><td>+33.3%</td></tr></table><h2>2. セグメント別</h2><p>SaaS事業が売上の72%を占め、ARRは前年同期比25%増の42億円。解約率は1.8%と業界水準を下回る。</p><h2>3. 来期見通し</h2><p>売上高70億円、営業利益率20%を目標とする。</p><p>以上</p>` },
  { title: '製品品質管理基準書', industry: 'manufacturing', content: `<h1>製品品質管理基準書</h1><p><strong>文書番号:</strong> QMS-2026-001</p><p><strong>改訂:</strong> 第5版</p><h2>1. 受入検査基準</h2><table><tr><th>検査項目</th><th>基準値</th><th>測定方法</th></tr><tr><td>外観</td><td>傷・汚れなし</td><td>目視検査</td></tr><tr><td>寸法精度</td><td>±0.05mm</td><td>三次元測定</td></tr><tr><td>重量</td><td>±2%</td><td>電子天秤</td></tr><tr><td>耐久性</td><td>10万回以上</td><td>繰返試験</td></tr></table><h2>2. 工程内検査</h2><p>各工程においてSPC管理を実施し、Cp値1.33以上を維持する。異常値検出時は直ちにライン停止し、原因究明を行う。</p><p>以上</p>` },
  { title: 'コンサルティングレポート: DX推進提案', industry: 'consulting', content: `<h1>DXトランスフォーメーション推進提案書</h1><p><strong>提出先:</strong> 株式会社○○ 経営企画部</p><p><strong>作成:</strong> △△コンサルティング</p><h2>1. エグゼクティブサマリー</h2><p>貴社の業務プロセスを分析した結果、以下の3領域でDX推進による大幅な効率化が見込まれる。年間約2.5億円のコスト削減効果を試算。</p><h2>2. 現状課題</h2><ul><li>紙ベースの承認フロー（平均処理日数: 5.2日）</li><li>部門間のデータサイロ化</li><li>レガシーシステムの保守コスト増大</li></ul><h2>3. 提案施策</h2><ol><li>ワークフロー自動化（RPAの導入）</li><li>統合データ基盤の構築</li><li>クラウドマイグレーション</li></ol><h2>4. 投資対効果</h2><table><tr><th>施策</th><th>投資額</th><th>年間削減</th><th>ROI</th></tr><tr><td>RPA導入</td><td>3,000万</td><td>8,000万</td><td>267%</td></tr><tr><td>データ基盤</td><td>1.5億</td><td>1.2億</td><td>80%</td></tr><tr><td>クラウド化</td><td>5,000万</td><td>5,000万</td><td>100%</td></tr></table><p>以上</p>` },
  { title: '週次進捗報告書（第9週）', industry: 'general', content: `<h1>週次進捗報告書</h1><p><strong>報告期間:</strong> 2026年2月24日〜2月28日</p><p><strong>担当:</strong> 開発第2チーム</p><h2>1. 今週の成果</h2><ul><li>ユーザー認証モジュール v2.0 の実装完了</li><li>APIテストカバレッジ 85%→92%に改善</li><li>パフォーマンスボトルネックの特定及び対処（レスポンス40%改善）</li></ul><h2>2. 課題・リスク</h2><ul><li>外部API連携で断続的なタイムアウト発生（調査中）</li><li>QA人員が計画比1名不足</li></ul><h2>3. 来週の予定</h2><ul><li>決済モジュールの結合テスト開始</li><li>セキュリティレビュー実施</li><li>ステージング環境へのデプロイ</li></ul><p>以上</p>` },
  { title: '社内研修資料: プレゼンテーション技法', industry: 'general', content: `<h1>プレゼンテーション技法研修</h1><p><strong>研修日:</strong> 2026年3月7日 14:00〜16:00</p><h2>1. 構成の基本原則</h2><p>効果的なプレゼンテーションは「結論→根拠→詳細→まとめ」の順で構成する。聴衆の注意力は開始5分で最も高い。</p><h2>2. スライドデザイン</h2><ul><li>1スライド1メッセージの原則</li><li>フォントサイズは最小24pt</li><li>文字数は1スライドあたり最大40文字</li><li>視覚情報（グラフ・図解）を積極的に活用</li></ul><h2>3. デリバリー技術</h2><ul><li>アイコンタクト: 聴衆全体を3秒ずつ見渡す</li><li>声の抑揚: 重要なポイントでトーンを変える</li><li>間（ま）: キーメッセージの前後に2秒の間</li></ul><p>以上</p>` },
];

export function getRandomDummyDoc(industry) {
  let docs = dummyDocuments;
  if (industry && industry !== 'all') docs = docs.filter(d => d.industry === industry || d.industry === 'general');
  return docs[Math.floor(Math.random() * docs.length)];
}
export function getDummyDoc(index) { return dummyDocuments[index % dummyDocuments.length]; }
export default dummyDocuments;
